/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001a41',
        'secondary-fixed-dim': '#e9c400',
        'on-secondary': '#ffffff',
        'primary': '#0058bc',
        'primary-container': '#0070eb',
        'on-background': '#1a1c1b',
        'tertiary-fixed-dim': '#53e16f',
        'on-error-container': '#93000a',
        'secondary-container': '#fdd400',
        'on-tertiary-fixed-variant': '#00531c',
        'primary-fixed-dim': '#adc6ff',
        'outline': '#717786',
        'surface-variant': '#e2e3e1',
        'surface': '#f9f9f7',
        'surface-container-low': '#f4f4f2',
        'surface-bright': '#f9f9f7',
        'tertiary': '#006b27',
        'on-surface-variant': '#414755',
        'surface-container-high': '#e8e8e6',
        'on-secondary-fixed': '#221b00',
        'secondary-fixed': '#ffe170',
        'inverse-primary': '#adc6ff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f1f1ef',
        'on-tertiary-container': '#f7fff2',
        'tertiary-fixed': '#72fe88',
        'error': '#ba1a1a',
        'on-primary-container': '#fefcff',
        'outline-variant': '#c1c6d7',
        'on-tertiary-fixed': '#002107',
        'secondary': '#705d00',
        'primary-fixed': '#d8e2ff',
        'on-primary-fixed-variant': '#004493',
        'error-container': '#ffdad6',
        'surface-container': '#eeeeec',
        'surface-dim': '#dadad8',
        'on-error': '#ffffff',
        'tertiary-container': '#008733',
        'surface-container-highest': '#e2e3e1',
        'on-primary': '#ffffff',
        'on-surface': '#1a1c1b',
        'background': '#f9f9f7',
        'inverse-surface': '#2f3130',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#6f5c00',
        'surface-tint': '#005bc1',
        'on-secondary-fixed-variant': '#544600',
      },
      spacing: {
        'md': '24px',
        'gutter': '16px',
        'margin-desktop': '48px',
        'margin-mobile': '20px',
        'base': '8px',
        'xs': '4px',
        'lg': '40px',
        'sm': '12px',
        'xl': '64px',
      },
      fontFamily: {
        'headline-lg': ['Quicksand', 'sans-serif'],
        'headline-md': ['Quicksand', 'sans-serif'],
        'headline-lg-mobile': ['Quicksand', 'sans-serif'],
        'display': ['Quicksand', 'sans-serif'],
        'body-lg': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'body-md': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'label-caps': ['Atkinson Hyperlegible Next', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
